### PR TITLE
fixed resolving json converters (included issue #75)

### PR DESCRIPTION
**Pull request by Erifirin**
added explicit ordering of assemblies

### CODE REVIEW

**Comment by Erifirin** [comment]
tests failed due to "Setup Unity license" failed
image

**Comment by applejag** [comment]
> added explicit ordering of assemblies

Thanks for creating this PR! But what is the issue you're trying to solve here?

The code already does a `.Reverse()` to set some sort of ordering. So this new `.Order(Order)` seems a bit redundant.



> tests failed due to "Setup Unity license" issues image

Yes sorry. The unit tests require a sensitive value, which is not available when the PR is created by an outside contributor. When your PR is done, then I'll have to recreate it just so the tests can run

**Comment by Erifirin** [comment]
The order of assemblies in array is non-deterministic. In my case this leads to conflicts between convetrers from this repo and the same convetrers embedded in RiderFlow assemblies (as internal classes). Calling Reverse() doesn't solve the problem because it just reverses the array. In result, RiderFlow converters appear at top of the array and break everything.

My fix ensures that Newtonsoft.Json assemblies will be placed at the beginning of the list and mscorlib is at the end. I also left Reverse() so as not to break anything. But it seems useless to me.

**Comment by Erifirin** [comment]
Ok, let's look what `TypeCache._assemblies` contains right now in my project (without fix - reversed array): [reverse.txt](https://github.com/applejag/Newtonsoft.Json-for-Unity.Converters/files/14448691/reverse.txt) `JetBrains.RiderFlow.Repacked` assembly (with internal converters) is closer to beginning of the array than any `Newtonsoft.Json`. And this is a problem.

At the same time, this is what is written in the comments:
>                 // Reversing so we get last imported assembly first.
>                 // When searching for types we want to look in mscorlib last
>                 // and Newtonsoft.Json up as the first ones
To be honest, I don’t understand how a simple Reverse() can guarantee such sorting. Obviously, it can't. That's why i sort the array explicitly (reversed array + order fix): [reverse_and_order.txt](https://github.com/applejag/Newtonsoft.Json-for-Unity.Converters/files/14448994/reverse_and_order.txt).

But I agree that two sorts seems a bit redundant. I would remove Reverse() if its only purpose is to move Newtonsoft.Json and mscorlib. Here another file with `TypeCache._assemblies` content (wtih order, without reverse): 
[order.txt](https://github.com/applejag/Newtonsoft.Json-for-Unity.Converters/files/14449249/order.txt)

**Comment by applejag** [comment]
Wdyt? @Erifirin

**Comment by Erifirin** [comment]
Yes! Now it works as expected.
Your solution definitely looks better. Also if you don't mind, I would get rid of multiple calls assembly.GetName() to reduce allocations.

**Pull request merged**
